### ISSUE TITLE
patch not afected in windows 10 and after gtikraken version 6.5.3

### ISSUE THREAD

**Issue by Vaziria** [5cr1pt/GitCracken#28]

**Comment by nazirulfitrifauzi** [comment]
Same Issue here.. It says the key is expired

**Comment by Naografix** [comment]
Same here @5cr1pt we need you :D

**Comment by KirillMetrik** [comment]
Seems like GitKraken now uses some other means for checkinf license with server instead of `xhrPromiseRedux`. I have checked the patched result - the index.js file is properly patched but Fiddler still shows that GitKraken somehow manages to reach api.gitkraken.com/phone-home endpoint.

**Comment by sante85** [comment]
with 6.5.3, no open private repos

**Comment by Naografix** [comment]
Do you know where can we download 6.5.1 release? plz

**Comment by modernpk** [comment]
Is anyone working to fix this?

**Comment by VladimirLarionov** [comment]
The author made a new version of the patch 0.6. 2. Take here ___s://pastebin.com/u/KillWolfVlad. Works on Linux with kraken 6.5.3.

**Comment by modernpk** [comment]
@VladimirLarionov There is no instruction about how to use that. Can you please share the instructions?

**Comment by VladimirLarionov** [comment]
Manual for Linux.
1. Convert from Base64 to a file. (Possible here https://base64.guru/converter/decode/file)
2. Fix the appId file.ts, if an error occurs (fix it like this catch (e) line 36). This item is optional.
3. To Install Node.js 12 version or later
4. Remove the old Kraken with the purge command. (For example sudo apt-get purge gitkraken)
5. Install the version 6.5.3. start and close.
6. Accept the patch.
7. Use

**Comment by luyang93** [comment]
> Do you know where can we download 6.5.1 release? plz

https://iusethis.luo.ma/gitkraken/GitKraken-6.5.1.dmg
https://release.gitkraken.com/linux/GitKraken-v6.5.1.deb
https://release.gitkraken.com/win64/GitKrakenSetup-6.5.1.exe

**Comment by luyang93** [comment]
> Manual for Linux.
> 
> 1. Convert from Base64 to a file. (Possible here https://base64.guru/converter/decode/file)
> 2. Fix the appId file.ts, if an error occurs (fix it like this catch (e) line 36). This item is optional.
> 3. To Install Node.js 12 version or later
> 4. Remove the old Kraken with the purge command. (For example sudo apt-get purge gitkraken)
> 5. Install the version 6.5.3. start and close.
> 6. Accept the patch.
> 7. Use

Can you elaborate on step 2? What is appId file.ts

**Comment by Naografix** [comment]
> > Do you know where can we download 6.5.1 release? plz
> 
> https://iusethis.luo.ma/gitkraken/GitKraken-6.5.1.dmg
> https://release.gitkraken.com/linux/GitKraken-v6.5.1.deb
> https://release.gitkraken.com/win64/GitKrakenSetup-6.5.1.exe

Hum, v6.5.1 cannot be patched too. It's not working for me :(

**Comment by JourneyOver** [comment]
Actually it can, as that is the last version I am running and I patched it just fine. 6.5.1 is the last version that is patchable with the current methods.

What error are you getting @Naografix

**Comment by Naografix** [comment]
> Actually it can, as that is the last version I am running and I patched it just fine. 6.5.1 is the last version that is patchable with the current methods.
> 
> but hopefully someone can come along with a patcher for 6.5.2+ that'll work on every OS
> 
> What error are you getting @Naografix

I don't have any error, just it stay free edition

**Comment by JourneyOver** [comment]
not sure then sorry, patcher is working for me for 6.5.1 on multiple machines.

**Comment by VladimirLarionov** [comment]
> > Manual for Linux.
> > 
> > 1. Convert from Base64 to a file. (Possible here https://base64.guru/converter/decode/file)
> > 2. Fix the appId file.ts, if an error occurs (fix it like this catch (e) line 36). This item is optional.
> > 3. To Install Node.js 12 version or later
> > 4. Remove the old Kraken with the purge command. (For example sudo apt-get purge gitkraken)
> > 5. Install the version 6.5.3. start and close.
> > 6. Accept the patch.
> > 7. Use
> 
> Can you elaborate on step 2? What is appId file.ts

This file is located in the directory /src/appId.ts
In some cases (example issue #17, #27), the patch does not run, to avoid this, it is better to correct  the source code. See pull requests #18. Enjoy.

**Comment by Linjieqiang** [comment]
Same here @5cr1pt we need you :D

**Comment by KirillMetrik** [comment]
> Manual for Linux.
> 
> 1. Convert from Base64 to a file. (Possible here https://base64.guru/converter/decode/file)
> 2. Fix the appId file.ts, if an error occurs (fix it like this catch (e) line 36). This item is optional.
> 3. To Install Node.js 12 version or later
> 4. Remove the old Kraken with the purge command. (For example sudo apt-get purge gitkraken)
> 5. Install the version 6.5.3. start and close.
> 6. Accept the patch.
> 7. Use

Any solution for Windows please?

**Comment by shifenis** [comment]
> not sure then sorry, patcher is working for me for 6.5.1 on multiple machines.

This is not really true: I could patch but on the restart, it starts with 6.5.1. Any way to prevents updates?

**Comment by JourneyOver** [comment]
> > not sure then sorry, patcher is working for me for 6.5.1 on multiple machines.
> 
> This is not really true: I could patch but on the restart, it starts with 6.5.3. Any way to prevents updates?

Actually it is, seeing as how I've had it work on multiple machines just fine.

Ways to prevent updates:

Remove the update.exe located in `%localappdata%/gitkraken` (for windows)

or

Add `127.0.0.1 release.gitkraken.com` to your host file located in `C:\Windows\System32\drivers\etc` (for windows)

Either way works, and will prevent gitkraken from updating.

**Comment by shifenis** [comment]
> > > not sure then sorry, patcher is working for me for 6.5.1 on multiple machines.
> > 
> > 
> > This is not really true: I could patch but on the restart, it starts with 6.5.3. Any way to prevents updates?
> 
> Actually it is, seeing as how I've had it work on multiple machines just fine.
> 
> Ways to prevent updates:
> 
> Remove the update.exe located in `%localappdata%/gitkraken` (for windows)
> 
> or
> 
> Add `127.0.0.1 release.gitkraken.com` to your host file located in `C:\Windows\System32\drivers\etc` (for windows)
> 
> Either way works, and will prevent gitkraken from updating.

This works with Windows, any solution for MacOS? 
I didn’t specify my OS, sorry.

**Comment by JourneyOver** [comment]
> This works with Windows, any solution for MacOS?
> I didn’t specify my OS, sorry.

It works with any OS, you just need to either figure out where gitkraken is installed and delete the update.exe file or find out where your host file is found and edit it to include the `127.0.0.1 release.gitkraken.com` bit.

**Comment by shifenis** [comment]
The structure of GitKraken on MacOS isn't the same of Windows.

**Comment by luyang93** [comment]
> > > Manual for Linux.
> > > 
> > > 1. Convert from Base64 to a file. (Possible here https://base64.guru/converter/decode/file)
> > > 2. Fix the appId file.ts, if an error occurs (fix it like this catch (e) line 36). This item is optional.
> > > 3. To Install Node.js 12 version or later
> > > 4. Remove the old Kraken with the purge command. (For example sudo apt-get purge gitkraken)
> > > 5. Install the version 6.5.3. start and close.
> > > 6. Accept the patch.
> > > 7. Use
> > 
> > 
> > Can you elaborate on step 2? What is appId file.ts
> 
> This file is located in the directory ./src/appId.ts
> In some cases (example issue #17, #27), the patch does not run, to avoid this, it is better to correct the source code. See pull requests #18. Enjoy.

thks,I've successed, refer to https://github.com/5cr1pt/GitCracken/issues/23#issuecomment-585587260

**Comment by gkshi** [comment]
I think it will be useful.

1. Download v6.5.1 here (macos dmg)
[https://yadi.sk/d/8HLxSirthO2HFA](https://yadi.sk/d/8HLxSirthO2HFA)

2. sudo nano /etc/hosts
```127.0.0.1 release.axocdn.com```
(It blocks gitkraken auto update)

3. Patch gitkraken as usual (after first open)

I've tested and it works fine.

**Comment by jaybauson** [comment]
> I think it will be useful.
> 
> 1. Download v6.5.1 here (macos dmg)
>    https://yadi.sk/d/8HLxSirthO2HFA
> 2. sudo nano /etc/hosts
>    `127.0.0.1 release.axocdn.com`
>    (It blocks gitkraken auto update)
> 3. Patch gitkraken as usual (after first open)
> 
> I've tested and it works fine.

This is working! Thanks!

**Comment by iamjoshuabcxvii** [comment]
I just went back to version of 6.2.1 where the crack works, afterall, it already has features I want. But hopefully a newer crack for 6.5.3+ versions is available. hehe.

**Comment by luyang93** [comment]
> I just went back to version of 6.2.1 where the crack works, afterall, it already has features I want. But hopefully a newer crack for 6.5.3+ versions is available. hehe.

It worked on v6.5.3.I've tested on Win10 and Ubuntu.

**Comment by iamjoshuabcxvii** [comment]
> > I just went back to version of 6.2.1 where the crack works, afterall, it already has features I want. But hopefully a newer crack for 6.5.3+ versions is available. hehe.
> 
> It worked on v6.5.3.I've tested on Win10 and Ubuntu.

using version 0.6.1 of patch?. Nope, it did not on mine, I already tried reinstalling and then re-patching like 7-8 times already, not working. What else did you do?

**Comment by luyang93** [comment]
> > > I just went back to version of 6.2.1 where the crack works, afterall, it already has features I want. But hopefully a newer crack for 6.5.3+ versions is available. hehe.
> > 
> > 
> > It worked on v6.5.3.I've tested on Win10 and Ubuntu.
> 
> using version 0.6.1 of patch?. Nope, it did not on mine, I already tried reinstalling and then re-patching like 7-8 times already, not working. What else did you do?

https://github.com/5cr1pt/GitCracken/issues/28#issuecomment-589937202
this version worked on v6.5.3

**Comment by iamjoshuabcxvii** [comment]
> > > > I just went back to version of 6.2.1 where the crack works, afterall, it already has features I want. But hopefully a newer crack for 6.5.3+ versions is available. hehe.
> > > 
> > > 
> > > It worked on v6.5.3.I've tested on Win10 and Ubuntu.
> > 
> > 
> > using version 0.6.1 of patch?. Nope, it did not on mine, I already tried reinstalling and then re-patching like 7-8 times already, not working. What else did you do?
> 
> [#28 (comment)](https://github.com/5cr1pt/GitCracken/issues/28#issuecomment-589937202)
> this version worked on v6.5.3

Running yarn run gitcracken patcher is showing this error
$ node dist/bin/gitcracken.js patcher
internal/modules/cjs/loader.js:638
    throw err;
    ^

> Error: Cannot find module 'D:\Installers\Office Programs\Programming Development Environments\GitKraken 6.2 + Crack\GitCracken\GitCracken\dist\bin\gitcracken.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.



any idea to fix this?.

**Comment by luyang93** [comment]
> > > > > I just went back to version of 6.2.1 where the crack works, afterall, it already has features I want. But hopefully a newer crack for 6.5.3+ versions is available. hehe.
> > > > 
> > > > 
> > > > It worked on v6.5.3.I've tested on Win10 and Ubuntu.
> > > 
> > > 
> > > using version 0.6.1 of patch?. Nope, it did not on mine, I already tried reinstalling and then re-patching like 7-8 times already, not working. What else did you do?
> > 
> > 
> > [#28 (comment)](https://github.com/5cr1pt/GitCracken/issues/28#issuecomment-589937202)
> > this version worked on v6.5.3
> 
> Running yarn run gitcracken patcher is showing this error
> $ node dist/bin/gitcracken.js patcher
> internal/modules/cjs/loader.js:638
> throw err;
> ^
> 
> ```
> Error: Cannot find module '......GitCracken\GitCracken\dist\bin\gitcracken.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
> any idea to fix this?.

you should read the previous reply.
https://github.com/5cr1pt/GitCracken/issues/28#issuecomment-591041336

**Comment by iamjoshuabcxvii** [comment]
> > > > > > I just went back to version of 6.2.1 where the crack works, afterall, it already has features I want. But hopefully a newer crack for 6.5.3+ versions is available. hehe.
> > > > > 
> > > > > 
> > > > > It worked on v6.5.3.I've tested on Win10 and Ubuntu.
> > > > 
> > > > 
> > > > using version 0.6.1 of patch?. Nope, it did not on mine, I already tried reinstalling and then re-patching like 7-8 times already, not working. What else did you do?
> > > 
> > > 
> > > [#28 (comment)](https://github.com/5cr1pt/GitCracken/issues/28#issuecomment-589937202)
> > > this version worked on v6.5.3
> > 
> > 
> > Running yarn run gitcracken patcher is showing this error
> > $ node dist/bin/gitcracken.js patcher
> > internal/modules/cjs/loader.js:638
> > throw err;
> > ^
> > ```
> > Error: Cannot find module '......GitCracken\GitCracken\dist\bin\gitcracken.js'
> >     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
> >     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
> >     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
> >     at startup (internal/bootstrap/node.js:283:19)
> >     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> > error Command failed with exit code 1.
> > info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> > ```
> > 
> > 
> > any idea to fix this?.
> 
> you should read the previous reply.
> [#28 (comment)](https://github.com/5cr1pt/GitCracken/issues/28#issuecomment-591041336)

I thought that was just for linux only and I'm using windows 10. haha. 

But then finally got it and decoded the file and finally got 6.5.3 to work. Although it took me sometime to realize it supposed to be an archive, no wonder I got garbled text in the text editor as I opened the file in the editor as it is a bin file when i downloaded it, Also I thought the version 0.6.2 is already commited in this repo, and I thought to myself, ah, maybe the version on the patch is not just upgraded, turns out it just really 0.6.1. haha. Anywhow, why is 0.6.2 not pushed in this repo though?.

**Comment by KirillMetrik** [comment]
@iamjoshuabcxvii What kind of archive is it? I was trying to rename it to zip file but it told me the file was broken.

**Comment by iamjoshuabcxvii** [comment]
> @iamjoshuabcxvii What kind of archive is it? I was trying to rename it to zip file but it told me the file was broken.

its an xz file archive. You may open it using 7-zip. If you are using WIN-Rar, it sometimes happens even with non corrupted actual zip files. 7-zip is what I always use when that happens.

**Comment by luyang93** [comment]
> > > > > > > I just went back to version of 6.2.1 where the crack works, afterall, it already has features I want. But hopefully a newer crack for 6.5.3+ versions is available. hehe.
> > > > > > 
> > > > > > 
> > > > > > It worked on v6.5.3.I've tested on Win10 and Ubuntu.
> > > > > 
> > > > > 
> > > > > using version 0.6.1 of patch?. Nope, it did not on mine, I already tried reinstalling and then re-patching like 7-8 times already, not working. What else did you do?
> > > > 
> > > > 
> > > > [#28 (comment)](https://github.com/5cr1pt/GitCracken/issues/28#issuecomment-589937202)
> > > > this version worked on v6.5.3
> > > 
> > > 
> > > Running yarn run gitcracken patcher is showing this error
> > > $ node dist/bin/gitcracken.js patcher
> > > internal/modules/cjs/loader.js:638
> > > throw err;
> > > ^
> > > ```
> > > Error: Cannot find module '......GitCracken\GitCracken\dist\bin\gitcracken.js'
> > >     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
> > >     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
> > >     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
> > >     at startup (internal/bootstrap/node.js:283:19)
> > >     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> > > error Command failed with exit code 1.
> > > info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> > > ```
> > > 
> > > 
> > > any idea to fix this?.
> > 
> > 
> > you should read the previous reply.
> > [#28 (comment)](https://github.com/5cr1pt/GitCracken/issues/28#issuecomment-591041336)
> 
> I thought that was just for linux only and I'm using windows 10. haha.
> 
> But then finally got it and decoded the file and finally got 6.5.3 to work. Although it took me sometime to realize it supposed to be an archive, no wonder I got garbled text in the text editor as I opened the file in the editor as it is a bin file when i downloaded it, Also I thought the version 0.6.2 is already commited in this repo, and I thought to myself, ah, maybe the version on the patch is not just upgraded, turns out it just really 0.6.1. haha. Anywhow, why is 0.6.2 not pushed in this repo though?.

I said, it works on Win10.
https://github.com/5cr1pt/GitCracken/issues/28#issuecomment-591748511

**Comment by iamjoshuabcxvii** [comment]
> > > > > > > > I just went back to version of 6.2.1 where the crack works, afterall, it already has features I want. But hopefully a newer crack for 6.5.3+ versions is available. hehe.
> > > > > > > 
> > > > > > > 
> > > > > > > It worked on v6.5.3.I've tested on Win10 and Ubuntu.
> > > > > > 
> > > > > > 
> > > > > > using version 0.6.1 of patch?. Nope, it did not on mine, I already tried reinstalling and then re-patching like 7-8 times already, not working. What else did you do?
> > > > > 
> > > > > 
> > > > > [#28 (comment)](https://github.com/5cr1pt/GitCracken/issues/28#issuecomment-589937202)
> > > > > this version worked on v6.5.3
> > > > 
> > > > 
> > > > Running yarn run gitcracken patcher is showing this error
> > > > $ node dist/bin/gitcracken.js patcher
> > > > internal/modules/cjs/loader.js:638
> > > > throw err;
> > > > ^
> > > > ```
> > > > Error: Cannot find module '......GitCracken\GitCracken\dist\bin\gitcracken.js'
> > > >     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
> > > >     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
> > > >     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
> > > >     at startup (internal/bootstrap/node.js:283:19)
> > > >     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> > > > error Command failed with exit code 1.
> > > > info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> > > > ```
> > > > 
> > > > 
> > > > any idea to fix this?.
> > > 
> > > 
> > > you should read the previous reply.
> > > [#28 (comment)](https://github.com/5cr1pt/GitCracken/issues/28#issuecomment-591041336)
> > 
> > 
> > I thought that was just for linux only and I'm using windows 10. haha.
> > But then finally got it and decoded the file and finally got 6.5.3 to work. Although it took me sometime to realize it supposed to be an archive, no wonder I got garbled text in the text editor as I opened the file in the editor as it is a bin file when i downloaded it, Also I thought the version 0.6.2 is already commited in this repo, and I thought to myself, ah, maybe the version on the patch is not just upgraded, turns out it just really 0.6.1. haha. Anywhow, why is 0.6.2 not pushed in this repo though?.
> 
> I said, it works on Win10.
> [#28 (comment)](https://github.com/5cr1pt/GitCracken/issues/28#issuecomment-591748511)

I thought you were just assuming it would work in windows 10 as the comment you cited is an instruction for Linux. Also got stuck up on decoding the base64 file as I got it downloaded as a application.bin file on the site with garbled data, and I was likem this must be something that could only be opened via Linux, haha. I just recently noticed the file type mentioned in the files meta/details in the site hence I realize that it should be opened as an archive instead of as a plain text.

**Comment by luyang93** [comment]
command line on Win10 and Linux doesn't have too much difference.
![photo_2020-02-27_14-59-09](https://user-images.githubusercontent.com/39150988/75419864-bde06e00-5971-11ea-866e-3abd2b6a2b37.jpg)


> > > > > > > > > I just went back to version of 6.2.1 where the crack works, afterall, it already has features I want. But hopefully a newer crack for 6.5.3+ versions is available. hehe.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It worked on v6.5.3.I've tested on Win10 and Ubuntu.
> > > > > > > 
> > > > > > > 
> > > > > > > using version 0.6.1 of patch?. Nope, it did not on mine, I already tried reinstalling and then re-patching like 7-8 times already, not working. What else did you do?
> > > > > > 
> > > > > > 
> > > > > > [#28 (comment)](https://github.com/5cr1pt/GitCracken/issues/28#issuecomment-589937202)
> > > > > > this version worked on v6.5.3
> > > > > 
> > > > > 
> > > > > Running yarn run gitcracken patcher is showing this error
> > > > > $ node dist/bin/gitcracken.js patcher
> > > > > internal/modules/cjs/loader.js:638
> > > > > throw err;
> > > > > ^
> > > > > ```
> > > > > Error: Cannot find module '......GitCracken\GitCracken\dist\bin\gitcracken.js'
> > > > >     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
> > > > >     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
> > > > >     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
> > > > >     at startup (internal/bootstrap/node.js:283:19)
> > > > >     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> > > > > error Command failed with exit code 1.
> > > > > info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> > > > > ```
> > > > > 
> > > > > 
> > > > > any idea to fix this?.
> > > > 
> > > > 
> > > > you should read the previous reply.
> > > > [#28 (comment)](https://github.com/5cr1pt/GitCracken/issues/28#issuecomment-591041336)
> > > 
> > > 
> > > I thought that was just for linux only and I'm using windows 10. haha.
> > > But then finally got it and decoded the file and finally got 6.5.3 to work. Although it took me sometime to realize it supposed to be an archive, no wonder I got garbled text in the text editor as I opened the file in the editor as it is a bin file when i downloaded it, Also I thought the version 0.6.2 is already commited in this repo, and I thought to myself, ah, maybe the version on the patch is not just upgraded, turns out it just really 0.6.1. haha. Anywhow, why is 0.6.2 not pushed in this repo though?.
> > 
> > 
> > I said, it works on Win10.
> > [#28 (comment)](https://github.com/5cr1pt/GitCracken/issues/28#issuecomment-591748511)
> 
> I thought you were just assuming it would work in windows 10 as the comment you cited is an instruction for Linux. Also got stuck up on decoding the base64 file as I got it downloaded as a application.bin file on the site with garbled data, and I was like this must be something that could only be opened via Linux, haha. I just recently noticed the file type mentioned in the files meta/details in the site hence I realize that it should be opened as an archive instead of as a plain text.
> 
> Anyhow, for anyone reading this thread, I could affirm too that the decoded base64 file archive indeed works on Windows 10 and GitKrakens version 6.5.3, hehe.

**Comment by Naografix** [comment]
Someone can put a clear instructions for Windows plz.
To much message here with to much info ^^

Really thank you for your works

**Comment by luyang93** [comment]
first，install node.js



---Original---

**Comment by Naografix** [comment]
> first，install node.js
> […](#)
> ---Original--- From: "Naografix"<notifications@github.com&gt; Date: Thu, Feb 27, 2020 18:05 PM To: "5cr1pt/GitCracken"<GitCracken@noreply.github.com&gt;; Cc: "Comment"<comment@noreply.github.com&gt;;"luyang93"<510426762@qq.com&gt;; Subject: Re: [5cr1pt/GitCracken] patch not afected in windows 10 and after gtikraken version 6.5.3 (#28) Someone can put a clear instructions for Windows plz. To much message here with to much info ^^ Really thank you for your works — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

And? ^^

**Comment by luyang93** [comment]
cd gitcracken
rm yarn.lock
yarn install
yarn build
node dist/bin/gitcracken.js patcher --asar gitkraken/resources/app.asar


---Original---

**Comment by Naografix** [comment]
So it works for 6.5.3?

**Comment by luyang93** [comment]
yep



---Original---

**Comment by hungnguyen28895** [comment]
> Someone can put a clear instructions for Windows plz.
> To much message here with to much info ^^
> 
> Really thank you for your works

You can download GitCracken 0.6.2 here: 
https://drive.google.com/open?id=1TlwunJ-31Llbvgaj_3iinvrw86utF5hs

**Comment by JourneyOver** [comment]
For anyone still having issues or whatever, several people (including myself) have made updates forks that will work on 6.5.3

https://github.com/BoGnY/GitCracken
https://github.com/a9/GitCracken
https://github.com/JourneyOver/GitCracken

**Comment by luyang93** [comment]
> https://github.com/BoGnY/GitCracken
> https://github.com/a9/GitCracken
> https://github.com/JourneyOver/GitCracken

Be careful of DCMA.
https://github.com/github/dmca/blob/master/2018/2018-05-15-GitKraken.md

**Comment by JourneyOver** [comment]
> > [BoGnY/GitCracken](https://github.com/BoGnY/GitCracken)
> > [a9/GitCracken](https://github.com/a9/GitCracken)
> > [JourneyOver/GitCracken](https://github.com/JourneyOver/GitCracken)
> 
> Be careful of DCMA.
> [github/dmca:2018/2018-05-15-GitKraken.md@`master`](https://github.com/github/dmca/blob/master/2018/2018-05-15-GitKraken.md) [](/github/dmca/blob/HEAD@{2020-02-27T20:03:25Z}/2018/2018-05-15-GitKraken.md)

Egh, I'll prob go about moving my own fork to be hosted somewhere else eventually that can't/won't get taken down. So it's no issue for me either way.

**Comment by Robb110** [comment]
> Manual for Linux.
> 
> 1. Convert from Base64 to a file. (Possible here https://base64.guru/converter/decode/file)
> 2. Fix the appId file.ts, if an error occurs (fix it like this catch (e) line 36). This item is optional.
> 3. To Install Node.js 12 version or later
> 4. Remove the old Kraken with the purge command. (For example sudo apt-get purge gitkraken)
> 5. Install the version 6.5.3. start and close.
> 6. Accept the patch.
> 7. Use

Edit: Manual for Windows 10 for 6.5.3

The author made a new version of the patch 0.6. 2. Take here ___s://pastebin.com/u/KillWolfVlad.

1. Convert from Base64 to a file. (Possible here https://base64.guru/converter/decode/file)
2. Fix the appId.ts, if an error occurs (fix it like this catch (e) line 36). This item is optional.  I got this error and you can go under /src open "appId.ts" change "catch {" to "catch (e){" and save it.
3. Install latest version of Node if yout don't have it already.
4. Install/Reinstall GitKraken 6.5.3
5. Apply the patch as in README.MD "yarn install; yarn build;" and then run "node dist/src/gitcracken.js patcher" in the GitCracken folder of the patcher
6. Enjoy

**Comment by Codeh4ck** [comment]
> > Manual for Linux.
> > 
> > 1. Convert from Base64 to a file. (Possible here https://base64.guru/converter/decode/file)
> > 2. Fix the appId file.ts, if an error occurs (fix it like this catch (e) line 36). This item is optional.
> > 3. To Install Node.js 12 version or later
> > 4. Remove the old Kraken with the purge command. (For example sudo apt-get purge gitkraken)
> > 5. Install the version 6.5.3. start and close.
> > 6. Accept the patch.
> > 7. Use
> 
> Edit: Manual for Windows 10 for 6.5.3
> 
> The author made a new version of the patch 0.6. 2. Take here ___s://pastebin.com/u/KillWolfVlad.
> 
> 1. Convert from Base64 to a file. (Possible here https://base64.guru/converter/decode/file)
> 2. Fix the appId.ts, if an error occurs (fix it like this catch (e) line 36). This item is optional.  I got this error and you can go under /src open "appId.ts" change "catch {" to "catch (e){" and save it.
> 3. Install latest version of Node if yout don't have it already.
> 4. Install/Reinstall GitKraken 6.5.3
> 5. Apply the patch as in README.MD "yarn install; yarn build;" and then run "node dist/src/gitcracken.js patcher" in the GitCracken folder of the patcher
> 6. Enjoy

This actually does work. I just ran `yarn install` and `yarn build` and then `yarn gitcracken patcher` and it did the job.

**Comment by luyang93** [comment]
https://send.firefox.com/download/3235eeaccad2653c/#yvwwD1aL0WoU4ToiO6ZFqQ

**Comment by amarcosj** [comment]
> 
> 
> I build an app.asar on Gitkraken version 6.5.4
> https://send.firefox.com/download/3235eeaccad2653c/#yvwwD1aL0WoU4ToiO6ZFqQ
> Anyone can replace it with C:\Users*_Username_*\AppData\Local\gitkraken*_app-6.5.4_*\resources to test working well?
> Win 10

It worked on Win10! Thanks!

**Comment by caoyifeng007** [comment]
>     1. Base64

I got the 'Application.bin' converted from the Base64, and what to do with this 'Application.bin' ?

**Comment by caoyifeng007** [comment]
I got the 'Application.bin' converted from Base64 , then  what can I do with this .bin file?

**Comment by Robb110** [comment]
> I got the 'Application.bin' converted from Base64 , then what can I do with this .bin file?

Open it with an archive manager like 7zip or WinRAR, you will see inside an application folder with inside an GitCracken folder, and there is all you need.

**Comment by caoyifeng007** [comment]
> 
> 
> > I got the 'Application.bin' converted from Base64 , then what can I do with this .bin file?
> 
> Open it with an archive manager like 7zip or WinRAR, you will see inside an application folder with inside an GitCracken folder, and there is all you need.

should I rename it to 'Application.rar' ?

**Comment by Robb110** [comment]
> > > I got the 'Application.bin' converted from Base64 , then what can I do with this .bin file?
> > 
> > 
> > Open it with an archive manager like 7zip or WinRAR, you will see inside an application folder with inside an GitCracken folder, and there is all you need.
> 
> should I rename it to 'Application.rar' ?

Nope. Just you have to right click and select "Open with.." and then select your archive manager.

**Comment by caoyifeng007** [comment]
> 
> 
> > > > I got the 'Application.bin' converted from Base64 , then what can I do with this .bin file?
> > > 
> > > 
> > > Open it with an archive manager like 7zip or WinRAR, you will see inside an application folder with inside an GitCracken folder, and there is all you need.
> > 
> > 
> > should I rename it to 'Application.rar' ?
> 
> Nope. Just you have to right click and select "Open with.." and then select your archive manager.

I must miss something, I do as you say, but there is no application folder just a file.
here is my operations:
1. copy the string from [](https://pastebin.com/6mM1ucxi)
2. paste the string in [](https://base64.guru/converter/decode/file)
3. download the application.bin
Is that all right ？

**Comment by Robb110** [comment]
Oh god lol. Open the application.bin with 7zip or WinRAR or idk just an archive manager, inside you will have an folder named "application" maybe for you will appear the icon as a file, but it's not. Just double click on it and you will se the "GitCracken" folder

**Comment by caoyifeng007** [comment]
> 
> 
> Oh god lol. Open the application.bin with 7zip or WinRAR or idk just an archive manager, inside you will have an folder named "application" maybe for you will appear the icon as a file, but it's not. Just double click on it and you will se the "GitCracken" folder

Thank you for a ton !!!  I got it.

**Comment by Robb110** [comment]
> > Oh god lol. Open the application.bin with 7zip or WinRAR or idk just an archive manager, inside you will have an folder named "application" maybe for you will appear the icon as a file, but it's not. Just double click on it and you will se the "GitCracken" folder
> 
> Thank you for a ton !!! I got it.

No problem. You're welcome!! :D

**Comment by iBisho** [comment]
@luyang93 Could you upload it again as the link expired?

**Comment by vipreshjha** [comment]
From Where can i download version 6.5.3 for windows.

**Comment by josebyte** [comment]
The link https://release.gitkraken.com/win64/GitKrakenSetup-6.5.1.exe is broken
¿Anyone can share it?
